# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  swapi_py-app:
    image: swapi_py
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://swapi_py-postgresql:5432/swapi_py
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://swapi_py-postgresql:5432/swapi_py
      - JHIPSTER_CACHE_REDIS_SERVER=redis://swapi_py-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://swapi_py-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  swapi_py-postgresql:
    image: postgres:14.2
    # volumes:
    #   - ~/volumes/jhipster/swapi_py/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=swapi_py
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
  swapi_py-redis:
    image: redis:6.2.6
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6379:6379
